# Python versions for matrix
language: python
python:
  - "2.7"
  - "2.6"

# Django versions for matrix
env:
  - DJANGO_VERSION=1.4.16
  - DJANGO_VERSION=1.5.11
  - DJANGO_VERSION=1.6.8
  - DJANGO_VERSION=1.7.1

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -q Django==$DJANGO_VERSION --use-mirrors

# command to run tests, e.g. python setup.py test
script:
  - python manage.py test
